name: Run Crawler

on: 
  schedule:
    - cron: '00 14 * * *'  
  workflow_dispatch:       # 允許手動執行

permissions:
  contents: write  # ✅ 允許這個 workflow 有寫入 repo 權限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # ✅ 這會自動使用 GITHUB_TOKEN
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pytz requests pytrends

      - name: Run crawler
        run: python crawler.py

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update at $(TZ=Asia/Taipei date +'%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
          git push
